# -*- coding: utf-8 -*-
"""Image to Sketch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1foBx33iIQEjLTDKwZaTYurYSqV2uuGcZ
"""

import cv2
import matplotlib.pyplot as plt

# Read the image
image = cv2.imread("/content/Gauransh.png")

# Convert to grayscale
gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Invert the grayscale image
inverted = 255 - gray_image

# Apply Gaussian blur
blur = cv2.GaussianBlur(inverted, (21, 21), 0)

# Invert the blurred image
inverted_blurr = 255 - blur

# Create the pencil sketch
sketch = cv2.divide(gray_image, inverted_blurr, scale=256.0)

# Display both original and sketch images
plt.figure(figsize=(12, 6))

# Original image (converted to RGB for correct color display in matplotlib)
plt.subplot(1, 2, 1)
plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
plt.title("Original Image")
plt.axis('off')

# Sketch image
plt.subplot(1, 2, 2)
plt.imshow(sketch, cmap='gray')
plt.title("Pencil Sketch")
plt.axis('off')

plt.tight_layout()
plt.show()

